spring:
  application:
    name: TimeBlockingApp

  datasource:
    url: jdbc:mysql:// [...] :3306/timeblock_app_db?createDatabaseIfNotExist=true
    username: [...]
    password: [...]
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: [...]
            client-secret: [...]
            scope: profile, email
        provider:
          google:
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

server:
  port: 8080
  error:
    whitelabel:
      enabled: false

logging:
  level:
    org.springframework: info
    digital.vaidas.timeblock: info